### ISSUE TITLE
关于取sql中的数据问题

### ISSUE THREAD

**Issue by bmarkinominjie** [nsdictionary/CoreClass#2]
在我请求sql数据的时候，返回的是以下的错误
网络请求错误日志（code=1）：URL地址有错，要么服务器没有响应。总之连接就有错。
 请求URL=(null)?page=1
我想知道的是关于这个url是在哪里设置的，关于取这个sql中的数据，这个地方你能不能介绍的更详细一点

**Comment by CharlinFeng** [comment]
这个问题问的非常好，取数据，指的是是向模型取数据，模型可以从本地sql提供，也可以从网络服务器提供。

取数据非常复杂，其实是第4季需要介绍的内容：动态缓存

**Comment by bmarkinominjie** [comment]
帮忙看一下那个CoreClass中的delete数据操作，当我对数据库中的数据进行删除时，返回的结果是删除成功，但最后打印出来，数据库的总数还是七个条，我不知道是不是我操作错误，帮忙检查一下
    VideoUploadParam *param = [VideoUploadParam sharedVideoUpladParam];
    param.hostID = 6;
    BOOL result = [VideoUploadParam delete:param];
    if (result == YES) {
        NSLog(@"删除第六条成功");
    }else{
        NSLog(@"删除第六条失败");
    }
原来数据库中总共七条数据，但删除第六条，数据的条数依然是七条

**Comment by CharlinFeng** [comment]
如果你懂sql，你可以在框架内找到对应sql，然后执行sql查看情况。

**Comment by bmarkinominjie** [comment]
关于NSData类型的数据是和NSString一样存取么，我是将NSData类型的数据和NSString一样处理，但总显示：错误：你操作的模型NSData在数据库中没有对应的数据表！

**Comment by CharlinFeng** [comment]
没有支持blob数据哈，

**Comment by CharlinFeng** [comment]
@bmarkinominjie  重制中，本次会加入对NSData的支持！

**Comment by bmarkinominjie** [comment]
问一下你那个coreModel如果要查询的内容需要满足两个条件，能直接查询么。比如我想要查询表中@"titile = testTitle",@"accessToken=testAppToken"

**Comment by CharlinFeng** [comment]
where 即可，这个是sql基本语法,将你的条件放入where即可,如：

“id>10 and price<100"
@bmarkinominjie

**Comment by bmarkinominjie** [comment]
多谢，是sql的基本语法就行了
