### ISSUE TITLE
有一个疑问不知道可不可以解决

### ISSUE THREAD

**Issue by ZhipingYang** [nsdictionary/CoreClass#4]
就是级联查询的时候,student这个model可以使用一组pen model？
就像jsonmodel那样。

感谢你的分享

![qq20150708-1](https://cloud.githubusercontent.com/assets/9360037/8561514/61066ee2-2559-11e5-8f32-88caf2efb8ec.png)

**Comment by CharlinFeng** [comment]
你应该先试一下

**Comment by ZhipingYang** [comment]
我没有试过啊，就是感觉一个库不错就先star一下。呵呵

**Comment by CharlinFeng** [comment]
@ZhipingYang 重制中，本次会加入对NSAarray的支持！
