### ISSUE TITLE
关于数据库存储的问题

### ISSUE THREAD

**Issue by wh930201** [nsdictionary/CoreClass#5]
数据库存model的时候不能存数组是不？我model里存了个数组就崩了 数组注释掉就不崩了

错误：你操作的模型NSArray在数据库中没有对应的数据表！

**Comment by CharlinFeng** [comment]
此bug已知晓哈，应该是当时设计的时候遗漏了，我近期会补上的，谢谢

**Comment by CharlinFeng** [comment]
@wh930201  重制中，本次会加入对NSAarray的支持！
